# Generated by Django 3.1.1 on 2020-09-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='task title')),
                ('description', models.TextField(verbose_name='task description')),
                ('date_of_creation', models.DateField(auto_now_add=True, verbose_name='date of task creation')),
                ('status', models.CharField(choices=[('new', 'new'), ('planned', 'planned'), ('in progress', 'in progress'), ('completed', 'completed')], max_length=11, verbose_name='task status')),
                ('planned_completion_date', models.DateField(blank=True, null=True, verbose_name='planned task completion date')),
            ],
        ),
    ]
