# Generated by Django 3.1.1 on 2020-09-29 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='task title')),
                ('description', models.TextField(verbose_name='task description')),
                ('date_of_creation', models.DateField(auto_now_add=True, verbose_name='date of task creation')),
                ('status', models.CharField(choices=[('new', 'new'), ('planned', 'planned'), ('in progress', 'in progress'), ('completed', 'completed')], max_length=11, verbose_name='task status')),
                ('planned_completion_date', models.DateField(blank=True, null=True, verbose_name='planned task completion date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='task owner')),
            ],
        ),
    ]
