# Generated by Django 3.1.1 on 2020-09-29 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_change', models.DateTimeField(auto_now_add=True, verbose_name='date when the task was changed')),
                ('title', models.CharField(max_length=32, null=True, verbose_name='changed task title')),
                ('description', models.TextField(null=True, verbose_name='changed task description')),
                ('date_of_creation', models.DateField(auto_now_add=True, verbose_name='date of task creation')),
                ('status', models.CharField(max_length=11, null=True, verbose_name='changed task status')),
                ('planned_completion_date', models.DateField(blank=True, null=True, verbose_name='changed planned task completion date')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.task', verbose_name='task whose history is stored')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to=settings.AUTH_USER_MODEL, verbose_name='task history owner')),
            ],
        ),
    ]
