# Generated by Django 3.1.1 on 2020-09-30 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tasks.task', verbose_name='task whose history is stored'),
        ),
    ]
