# Generated by Django 3.1.2 on 2020-10-13 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20200930_0839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='date_of_creation',
        ),
    ]
