# Generated by Django 3.1.2 on 2020-10-13 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_history_date_of_creation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='user',
        ),
    ]
